### ISSUE TITLE
bb next release checklist

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#991]
- [x] merge new JDK 11 client
- [x] upgrade to GraalVM 21.2 to re-gain 5 mbs (which are taken by the new JDK 11 client)
- [x] Add java-http-clj lib to CI tests (at least loading the code + some manual tests, similar to the raw interop ones)
- [x] https://github.com/babashka/babashka/issues/995
- [x] update changelogs
- [x] update news page
- [x] upgrade the deps.clj related stuff to newest clojure CLI parity
